### ISSUE TITLE
how do you use this

### ISSUE THREAD

**Issue by RakiiTheGit** [imAETHER/AI-CaptchaSolver#6]

**Comment by RakiiTheGit** [comment]
so im trying to go to a roblox script server (lalol hub) and the captha is hard and idk how to use this

**Comment by RakiiTheGit** [comment]
wait i acctedently closed this issue

**Comment by RakiiTheGit** [comment]
so im trying to go to a roblox script server (lalol hub) and the captcha is hard and idk how to use this

**Comment by imAETHER** [comment]
can you show a few images for the captchas youre trying to solve?

**Comment by RakiiTheGit** [comment]
> can you show a few images for the captchas youre trying to solve?

here 
![Screenshot 2024-11-11 195446](https://github.com/user-attachments/assets/5735ab37-1bc3-448a-9978-c3d476819988)
![Screenshot 2024-11-11 193926](https://github.com/user-attachments/assets/8df2363a-1421-4534-b06a-9615f8aa999a)

**Comment by RakiiTheGit** [comment]
wait nvm
